import type { Metadata } from "next";
import "../assets/styles/global.scss";
import "../assets/styles/variable.scss";
import { Layout } from "@/components/Templates/Layout";

export const metadata: Metadata = {
  title: "Study Tracker Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
