import type { Metadata } from "next";
import "../assets/styles/reset.scss";
import { Layout } from "@/components/parts/Layout";

export const metadata: Metadata = {
  title: "Study Tracker Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Layout>{children}</Layout>
    </html>
  );
}
