name: CI

run-name: ${{ github.actor }} has pushed on ${{ github.ref }}

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリを取得
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js 環境をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3. 依存関係をインストール
      - name: Install dependencies
        run: npm ci

      # 4. Lint
      - name: Run ESLint
        run: npm run lint

      # 5. 型チェック
      # - name: Type check
      #   run: npx tsc --noEmit

      # 6. テスト (Vitest)
      - name: Run tests
        run: npm run test -- --coverage

      # 7. ビルド確認
      - name: Build
        run: npm run build
